#include <stdio.h>
#include "csmith.h"
#include <stdlib.h>


/* --- Struct/Union Declarations --- */
struct S0 {
	unsigned f0 : 1;
	int f1 : 32;
};

struct S1 {
	int f0 : 8;
	volatile int f1 : 24;
	unsigned const f2 : 22;
};

union U0 {
	int f0;
	unsigned f1;
};

union U1 {
	unsigned f0;
	const int f1;
};

/* --- GLOBAL VARIABLES --- */
static int g0 = 345; 
static const int g1 = 89; 
static int g2[3] = {0, 1, 2}; 
static struct S0 g3 = {1, 2}; 
static struct S1 g4[2][2] = {{{1,2,3},{1,2,3}}, {{1,2,3},{1,2,3}}};	    
static union U0 g5 = {22}; 
static struct S1 g6 = {4, 5, 46};
static union U1 g7[3] = {22, 23, 24};

/* --- FORWARD DECLARATIONS --- */

int main (int argc, char* argv[]){

    /* START AUTOGENERATED CODE BY S2S TRANSLATION */
    int s2s_nr_inputs = 17;
    int *s2s_input = (int *) calloc(s2s_nr_inputs, sizeof(int));
    FILE *s2s_file = fopen(argv[1], "r");
    char s2s_buffer[100];
    int s2s_i = 0;
    while((fgets(s2s_buffer, 100 - 1, s2s_file) != NULL) && s2s_i < s2s_nr_inputs) {
        s2s_input[s2s_i] = atoi(s2s_buffer);
        s2s_i++;
    }
    fclose(s2s_file);
    g0 = s2s_input[0];
    g2[0] = s2s_input[1];
    g2[1] = s2s_input[2];
    g2[2] = s2s_input[3];
    g3.f0 = s2s_input[4];
    g3.f1 = s2s_input[5];
    g4[0][0].f0 = s2s_input[6];
    g4[0][0].f1 = s2s_input[7];
    g4[0][1].f0 = s2s_input[8];
    g4[0][1].f1 = s2s_input[9];
    g4[1][0].f0 = s2s_input[10];
    g4[1][0].f1 = s2s_input[11];
    g4[1][1].f0 = s2s_input[12];
    g4[1][1].f1 = s2s_input[13];
    g5.f0 = s2s_input[14];
    g6.f0 = s2s_input[15];
    g6.f1 = s2s_input[16];
    free(s2s_input);
    /* END AUTOGENERATED CODE BY S2S TRANSLATION */

	if (g2[1] + g3.f0 < 45){
		printf("g2[1] + g3.f0 < 45)\n");
	} else if (g5.f1 == g3.f1){
		printf("g5.f1 == g3.f1\n");
	}
	
	if (g4[0][0].f1 == g6.f1){
		printf("g4[0][0].f1 == g6.f1\n");
	} else {
		if (g0 - 1 == 22){
			printf("(g4[0][0].f1 != g6.f1)"
			       "&& (g0 - 1 == 22)\n");
		} else {
			printf("(g4[0][0].f1 != g6.f1)"
			       "&& (g0 - 1 != 22)\n");
		}
	}
	
	if (g1 == g7[2].f0){
		printf("g1 == g7[2].f0\n");
	} else {
		printf("g1 != g7[2].f0\n");
	}
	
	return 0;
}
	

